keycloak:
  auth-server-url: ${embedded.keycloak.auth-server-url}
  realm: spring_keycloak-testing-realm
  resource: spring_keycloak-test-client
  use-resource-role-mappings: true
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${embedded.keycloak.auth-server-url}/realms/spring_keycloak-testing-realm/protocol/openid-connect/certs

server.forward-headers-strategy: FRAMEWORK
server.port: 8000

logging:
  level:
    com.playtika.test: info
    org.springframework.boot: info
    org.springframework.security: info
    org.keycloak: debug
    root: info
